#!/usr/bin/env bash
# scripts/refresh_artefacts.sh — pull a year of data and regenerate every
# checked-in deliverable (REPORT.md, dashboard.html, charts).
#
# Run from the repo root. Network access to Polymarket gamma + CLOB +
# Hyperliquid /info is required. Idempotent: every CLI command writes its
# own rows or replaces its own artefact, so re-running is safe.
#
# Usage:
#   bash scripts/refresh_artefacts.sh                  # default DB path
#   bash scripts/refresh_artefacts.sh /tmp/foo.db      # custom DB path
#
# Tunables via env:
#   COINS         comma-list of HL perps to pull (default: 12 majors)
#   DAYS          history window in days (default: 365)
#   FEE_BUFFER    paper-trading flagged-event buffer (default: 0.005)
#   SKIP_MONITOR  set to 1 to skip the forward orderbook-capture step

set -euo pipefail

DB="${1:-polymarket_edge.db}"
COINS="${COINS:-BTC,ETH,SOL,XRP,DOGE,AVAX,BNB,LINK,ARB,OP,SUI,TRX}"
DAYS="${DAYS:-365}"
FEE_BUFFER="${FEE_BUFFER:-0.005}"
SKIP_MONITOR="${SKIP_MONITOR:-1}"   # default off — forward-only, slow

echo "==> refresh_artefacts: DB=${DB}  coins=${COINS}  days=${DAYS}"
echo

step() { echo; echo "==> $*"; }

step "Hyperliquid — universe + funding snapshot (writes hl_universe_snapshots)"
uv run polymarket-edge hl-ingest --db-path "${DB}"

step "Hyperliquid — ${DAYS}d of funding history for ${COINS}"
uv run polymarket-edge hl-history \
    --db-path "${DB}" \
    --coins "${COINS}" \
    --days "${DAYS}"

step "Hyperliquid — headline backtest"
uv run polymarket-edge hl-backtest --db-path "${DB}"

step "Hyperliquid — block-bootstrap CI"
uv run polymarket-edge hl-ci-block --db-path "${DB}" --n-resamples 5000

step "Hyperliquid — walk-forward OOS"
uv run polymarket-edge walk-forward \
    --db-path "${DB}" \
    --train-days 60 --test-days 30 --step-days 14

step "Hyperliquid — tail risk"
uv run polymarket-edge hl-tail --db-path "${DB}" --spread-bps-per-leg 5

step "Hyperliquid — cadence frontier (the deployable finding)"
uv run polymarket-edge hl-cadence-frontier \
    --db-path "${DB}" \
    --out cadence_frontier.png

step "Polymarket — gamma event ingest"
uv run polymarket-edge ingest --db-path "${DB}"

step "Polymarket — scan for current arb signals"
uv run polymarket-edge scan --db-path "${DB}"

step "Polymarket — microstructure scan (real / marginal / trap classification)"
uv run polymarket-edge microstructure-scan --db-path "${DB}"

step "Polymarket — trap classifier with negative-control AUC"
uv run polymarket-edge trap-predict --db-path "${DB}" || true

if [ "${SKIP_MONITOR}" != "1" ]; then
    step "Polymarket — 60 minutes of forward orderbook capture (book_snapshots)"
    uv run polymarket-edge monitor \
        --db-path "${DB}" \
        --duration-minutes 60 \
        --capture-books
fi

step "Regenerate research note + dashboard"
uv run polymarket-edge report    --db-path "${DB}" --out REPORT.md
uv run polymarket-edge dashboard --db-path "${DB}" --out dashboard.html

echo
echo "==> done. Artefacts:"
echo "    REPORT.md"
echo "    dashboard.html"
echo "    cadence_frontier.png"
echo "    funding_apr_per_coin.png  (regenerated by 'report')"
echo "    hl_cumulative_pnl.png     (regenerated by 'report')"
